# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080

spring:
  #数据源和jpa配置
  datasource:
    #数据库相关的配置url  -SSL连接设置为false
    url: jdbc:mysql://localhost:3306/algorithm?characterEncoding=utf8&useSSL=false
    #配置用户名
    username: root
    #配置密码
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #下面为连接池相关配置
  dbcp2:
    #初始化连接池大小
    initial-size: 10
    #陪住最小连接池数
    min-idle: 10
    #配置最大连接池数
    max-idle: 30
    #配置获取超时连接的等待时间
    max-wait-millis: 30000
    #配置多长时间进行一次检测,检测需要关闭的数据库连接
    time-between-eviction-runs-millis: 200000
  jpa:
      #配置数据库类型
      database: MYSQL
      #配置是否打印sql
      show-sql: true
      #Hibernate相关配置
      hibernate:
        #配置级联等级
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect